package com.schemaforge.export.strategy.impl;

import com.schemaforge.export.entity.ExportDialect;
import com.schemaforge.export.strategy.SqlBuilderSupport;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class SqlServerExportStrategy extends SqlBuilderSupport {

    @Override
    public ExportDialect getDialect() {
        return ExportDialect.SQLSERVER;
    }

    @Override
    protected String quoteIdentifier(String name) {
        return "[" + name + "]";
    }

    @Override
    protected String mapColumnType(String aiType) {
        if (aiType == null) return "NVARCHAR(255)";
        return switch (aiType.toUpperCase().trim()) {
            case "UUID"                              -> "UNIQUEIDENTIFIER";
            case "INT", "INTEGER"                    -> "INT";
            case "BIGINT"                            -> "BIGINT";
            case "SMALLINT"                          -> "SMALLINT";
            case "DECIMAL", "NUMERIC"                -> "DECIMAL(19,4)";
            case "FLOAT", "DOUBLE", "REAL"           -> "FLOAT";
            case "BOOLEAN", "BOOL"                   -> "BIT";
            case "TEXT"                              -> "NVARCHAR(MAX)";
            case "DATE"                              -> "DATE";
            case "TIME"                              -> "TIME";
            case "TIMESTAMP", "DATETIME", "TIMESTAMPTZ" -> "DATETIME2";
            case "JSONB", "JSON"                     -> "NVARCHAR(MAX)";
            case "SERIAL"                            -> "INT IDENTITY(1,1)";
            case "BIGSERIAL"                         -> "BIGINT IDENTITY(1,1)";
            default -> aiType.toUpperCase().startsWith("VARCHAR")
                    ? aiType.toUpperCase().replace("VARCHAR", "NVARCHAR")
                    : "NVARCHAR(255)";
        };
    }

    @Override
    protected String autoIncrementClause() {
        return "IDENTITY(1,1)";
    }

    @Override
    protected String adaptIndex(String rawIndex) {
        // Replace double-quoted identifiers with bracket-quoted ones.
        return rawIndex.replace("\"", "").replaceAll("(\\w+)", "[$1]")
                .replace("[CREATE]", "CREATE")
                .replace("[INDEX]", "INDEX")
                .replace("[ON]", "ON")
                .replace("[UNIQUE]", "UNIQUE")
                + ";";
    }

    @Override
    protected void appendHeader(StringBuilder sb, String systemName, String description) {
        sb.append("-- ================================================================").append(NEWLINE);
        sb.append("-- ").append(systemName != null ? systemName : "Generated Schema").append(NEWLINE);
        if (description != null && !description.isBlank()) {
            sb.append("-- ").append(description).append(NEWLINE);
        }
        sb.append("-- Generated by SchemaForge AI").append(NEWLINE);
        sb.append("-- ================================================================").append(NEWLINE);
        sb.append("USE [YourDatabaseName];").append(NEWLINE);
        sb.append("GO").append(NEWLINE);
        sb.append(NEWLINE);
    }

    @Override
    protected void appendCreateTable(StringBuilder sb, java.util.Map<String, Object> table) {
        super.appendCreateTable(sb, table);
        sb.append("GO").append(NEWLINE);
    }
}