package com.schemaforge.activity.entity;

public enum ActivityType {

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_DELETED,

    SCHEMA_CREATED,
    SCHEMA_UPDATED,
    SCHEMA_GENERATED,
    SCHEMA_GENERATION_FAILED,
    SCHEMA_DELETED,
    SCHEMA_RESTORED,

    EXPORT_CREATED,
    EXPORT_FAILED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,

    TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED,
    TEAM_MEMBER_ROLE_CHANGED,

    INVITATION_SENT,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_REVOKED,

    USER_LOGIN,

    SYSTEM_EVENT
}