package com.schemaforge.export.strategy;

import com.schemaforge.schema.entity.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Shared parsing and SQL building helpers for all dialect strategies.
 *
 * The Schema entity stores tables as List<Map<String,Object>> where each map has:
 *   name        : String  — table name
 *   description : String  — optional comment
 *   fields      : List<Map> — each field has name, type, constraints[], description, references?
 *   indexes     : List<String> — raw CREATE INDEX statements (dialect-specific)
 *
 * Relationships are List<Map<String,Object>> where each map has:
 *   from        : String  — referencing table
 *   to          : String  — referenced table
 *   type        : String  — one-to-one | one-to-many | many-to-many
 *   description : String
 *
 * FK constraints are derived from field.references ("table.column") when present,
 * not from the relationships list (which is for diagram/documentation purposes).
 */
public abstract class SqlBuilderSupport implements ExportDialectStrategy {

    protected static final String NEWLINE = System.lineSeparator();

    // -------------------------------------------------------------------------
    // Template method — subclasses override dialect-specific parts
    // -------------------------------------------------------------------------

    @Override
    public final String generateSql(Schema schema) {
        StringBuilder sb = new StringBuilder();

        appendHeader(sb, schema.getSystemName(), schema.getDescription());

        List<Map<String, Object>> tables = schema.getTables();
        if (tables == null || tables.isEmpty()) {
            sb.append("-- No tables found in schema").append(NEWLINE);
            return sb.toString();
        }

        for (Map<String, Object> table : tables) {
            appendCreateTable(sb, table);
            sb.append(NEWLINE);
        }

        for (Map<String, Object> table : tables) {
            List<String> indexes = extractIndexes(table);
            for (String idx : indexes) {
                sb.append(adaptIndex(idx)).append(NEWLINE);
            }
        }

        appendFooter(sb);
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Extension points
    // -------------------------------------------------------------------------

    protected abstract String quoteIdentifier(String name);

    protected abstract String mapColumnType(String aiType);

    protected abstract String autoIncrementClause();

    protected abstract String adaptIndex(String rawIndex);

    // -------------------------------------------------------------------------
    // Shared implementation
    // -------------------------------------------------------------------------

    protected void appendHeader(StringBuilder sb, String systemName, String description) {
        sb.append("-- ================================================================").append(NEWLINE);
        sb.append("-- ").append(systemName != null ? systemName : "Generated Schema").append(NEWLINE);
        if (description != null && !description.isBlank()) {
            sb.append("-- ").append(description).append(NEWLINE);
        }
        sb.append("-- Generated by SchemaForge AI").append(NEWLINE);
        sb.append("-- ================================================================").append(NEWLINE);
        sb.append(NEWLINE);
    }

    protected void appendFooter(StringBuilder sb) {
        // Default: no-op. Subclasses may append dialect-specific footers.
    }

    @SuppressWarnings("unchecked")
    protected void appendCreateTable(StringBuilder sb, Map<String, Object> table) {
        String tableName = (String) table.get("name");
        String description = (String) table.get("description");
        List<Map<String, Object>> fields = (List<Map<String, Object>>) table.getOrDefault("fields", List.of());

        if (description != null && !description.isBlank()) {
            sb.append("-- ").append(description).append(NEWLINE);
        }

        sb.append("CREATE TABLE ").append(quoteIdentifier(tableName)).append(" (").append(NEWLINE);

        List<String> columnDefs = new ArrayList<>();
        List<String> fkConstraints = new ArrayList<>();
        List<String> pkColumns = new ArrayList<>();

        for (Map<String, Object> field : fields) {
            columnDefs.add(buildColumnDefinition(field, tableName));

            List<String> constraints = extractConstraints(field);
            if (constraints.stream().anyMatch(c -> c.toUpperCase().contains("PRIMARY KEY"))) {
                pkColumns.add(quoteIdentifier((String) field.get("name")));
            }

            String references = (String) field.get("references");
            if (references != null && !references.isBlank()) {
                fkConstraints.add(buildForeignKey(tableName, (String) field.get("name"), references));
            }
        }

        // column definitions
        for (int i = 0; i < columnDefs.size(); i++) {
            boolean last = i == columnDefs.size() - 1 && fkConstraints.isEmpty();
            sb.append("    ").append(columnDefs.get(i));
            sb.append(last ? "" : ",").append(NEWLINE);
        }

        // inline FK constraints
        for (int i = 0; i < fkConstraints.size(); i++) {
            boolean last = i == fkConstraints.size() - 1;
            sb.append("    ").append(fkConstraints.get(i));
            sb.append(last ? "" : ",").append(NEWLINE);
        }

        sb.append(");").append(NEWLINE);
    }

    @SuppressWarnings("unchecked")
    protected String buildColumnDefinition(Map<String, Object> field, String tableName) {
        String name = (String) field.get("name");
        String type = mapColumnType((String) field.getOrDefault("type", "VARCHAR(255)"));
        List<String> constraints = extractConstraints(field);

        StringBuilder col = new StringBuilder();
        col.append(quoteIdentifier(name)).append(" ").append(type);

        boolean isPk = constraints.stream().anyMatch(c -> c.toUpperCase().contains("PRIMARY KEY"));
        boolean isNotNull = constraints.stream().anyMatch(c -> c.toUpperCase().contains("NOT NULL"));
        boolean isUnique = constraints.stream().anyMatch(c -> c.toUpperCase().contains("UNIQUE"));

        if (isPk) {
            col.append(" PRIMARY KEY");
        }
        if (isNotNull && !isPk) {
            col.append(" NOT NULL");
        }
        if (isUnique && !isPk) {
            col.append(" UNIQUE");
        }

        return col.toString();
    }

    protected String buildForeignKey(String tableName, String columnName, String references) {
        // references format: "other_table.column" or just "other_table"
        String[] parts = references.split("\\.");
        String refTable = parts[0].trim();
        String refColumn = parts.length > 1 ? parts[1].trim() : "id";

        String constraintName = "fk_" + tableName + "_" + columnName;
        return "CONSTRAINT " + quoteIdentifier(constraintName)
                + " FOREIGN KEY (" + quoteIdentifier(columnName) + ")"
                + " REFERENCES " + quoteIdentifier(refTable) + " (" + quoteIdentifier(refColumn) + ")";
    }

    @SuppressWarnings("unchecked")
    protected List<String> extractConstraints(Map<String, Object> field) {
        Object raw = field.get("constraints");
        if (raw instanceof List<?> list) {
            return list.stream().map(Object::toString).toList();
        }
        return List.of();
    }

    @SuppressWarnings("unchecked")
    protected List<String> extractIndexes(Map<String, Object> table) {
        Object raw = table.get("indexes");
        if (raw instanceof List<?> list) {
            return list.stream().map(Object::toString).toList();
        }
        return List.of();
    }
}